// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"flashcards-backend/ent/cardstatus"
	"flashcards-backend/ent/predicate"
	"flashcards-backend/ent/user"
	"flashcards-backend/ent/word"
	"fmt"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// CardStatusUpdate is the builder for updating CardStatus entities.
type CardStatusUpdate struct {
	config
	hooks      []Hook
	mutation   *CardStatusMutation
	predicates []predicate.CardStatus
}

// Where adds a new predicate for the builder.
func (csu *CardStatusUpdate) Where(ps ...predicate.CardStatus) *CardStatusUpdate {
	csu.predicates = append(csu.predicates, ps...)
	return csu
}

// SetDoneLast sets the done_last field.
func (csu *CardStatusUpdate) SetDoneLast(t time.Time) *CardStatusUpdate {
	csu.mutation.SetDoneLast(t)
	return csu
}

// SetUserID sets the user edge to User by id.
func (csu *CardStatusUpdate) SetUserID(id int) *CardStatusUpdate {
	csu.mutation.SetUserID(id)
	return csu
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (csu *CardStatusUpdate) SetNillableUserID(id *int) *CardStatusUpdate {
	if id != nil {
		csu = csu.SetUserID(*id)
	}
	return csu
}

// SetUser sets the user edge to User.
func (csu *CardStatusUpdate) SetUser(u *User) *CardStatusUpdate {
	return csu.SetUserID(u.ID)
}

// SetCardID sets the card edge to Word by id.
func (csu *CardStatusUpdate) SetCardID(id int) *CardStatusUpdate {
	csu.mutation.SetCardID(id)
	return csu
}

// SetNillableCardID sets the card edge to Word by id if the given value is not nil.
func (csu *CardStatusUpdate) SetNillableCardID(id *int) *CardStatusUpdate {
	if id != nil {
		csu = csu.SetCardID(*id)
	}
	return csu
}

// SetCard sets the card edge to Word.
func (csu *CardStatusUpdate) SetCard(w *Word) *CardStatusUpdate {
	return csu.SetCardID(w.ID)
}

// Mutation returns the CardStatusMutation object of the builder.
func (csu *CardStatusUpdate) Mutation() *CardStatusMutation {
	return csu.mutation
}

// ClearUser clears the user edge to User.
func (csu *CardStatusUpdate) ClearUser() *CardStatusUpdate {
	csu.mutation.ClearUser()
	return csu
}

// ClearCard clears the card edge to Word.
func (csu *CardStatusUpdate) ClearCard() *CardStatusUpdate {
	csu.mutation.ClearCard()
	return csu
}

// Save executes the query and returns the number of rows/vertices matched by this operation.
func (csu *CardStatusUpdate) Save(ctx context.Context) (int, error) {

	var (
		err      error
		affected int
	)
	if len(csu.hooks) == 0 {
		affected, err = csu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CardStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			csu.mutation = mutation
			affected, err = csu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(csu.hooks) - 1; i >= 0; i-- {
			mut = csu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, csu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (csu *CardStatusUpdate) SaveX(ctx context.Context) int {
	affected, err := csu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (csu *CardStatusUpdate) Exec(ctx context.Context) error {
	_, err := csu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csu *CardStatusUpdate) ExecX(ctx context.Context) {
	if err := csu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (csu *CardStatusUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cardstatus.Table,
			Columns: cardstatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cardstatus.FieldID,
			},
		},
	}
	if ps := csu.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := csu.mutation.DoneLast(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: cardstatus.FieldDoneLast,
		})
	}
	if csu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardstatus.UserTable,
			Columns: []string{cardstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := csu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardstatus.UserTable,
			Columns: []string{cardstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if csu.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cardstatus.CardTable,
			Columns: []string{cardstatus.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: word.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := csu.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cardstatus.CardTable,
			Columns: []string{cardstatus.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: word.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, csu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cardstatus.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return 0, err
	}
	return n, nil
}

// CardStatusUpdateOne is the builder for updating a single CardStatus entity.
type CardStatusUpdateOne struct {
	config
	hooks    []Hook
	mutation *CardStatusMutation
}

// SetDoneLast sets the done_last field.
func (csuo *CardStatusUpdateOne) SetDoneLast(t time.Time) *CardStatusUpdateOne {
	csuo.mutation.SetDoneLast(t)
	return csuo
}

// SetUserID sets the user edge to User by id.
func (csuo *CardStatusUpdateOne) SetUserID(id int) *CardStatusUpdateOne {
	csuo.mutation.SetUserID(id)
	return csuo
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (csuo *CardStatusUpdateOne) SetNillableUserID(id *int) *CardStatusUpdateOne {
	if id != nil {
		csuo = csuo.SetUserID(*id)
	}
	return csuo
}

// SetUser sets the user edge to User.
func (csuo *CardStatusUpdateOne) SetUser(u *User) *CardStatusUpdateOne {
	return csuo.SetUserID(u.ID)
}

// SetCardID sets the card edge to Word by id.
func (csuo *CardStatusUpdateOne) SetCardID(id int) *CardStatusUpdateOne {
	csuo.mutation.SetCardID(id)
	return csuo
}

// SetNillableCardID sets the card edge to Word by id if the given value is not nil.
func (csuo *CardStatusUpdateOne) SetNillableCardID(id *int) *CardStatusUpdateOne {
	if id != nil {
		csuo = csuo.SetCardID(*id)
	}
	return csuo
}

// SetCard sets the card edge to Word.
func (csuo *CardStatusUpdateOne) SetCard(w *Word) *CardStatusUpdateOne {
	return csuo.SetCardID(w.ID)
}

// Mutation returns the CardStatusMutation object of the builder.
func (csuo *CardStatusUpdateOne) Mutation() *CardStatusMutation {
	return csuo.mutation
}

// ClearUser clears the user edge to User.
func (csuo *CardStatusUpdateOne) ClearUser() *CardStatusUpdateOne {
	csuo.mutation.ClearUser()
	return csuo
}

// ClearCard clears the card edge to Word.
func (csuo *CardStatusUpdateOne) ClearCard() *CardStatusUpdateOne {
	csuo.mutation.ClearCard()
	return csuo
}

// Save executes the query and returns the updated entity.
func (csuo *CardStatusUpdateOne) Save(ctx context.Context) (*CardStatus, error) {

	var (
		err  error
		node *CardStatus
	)
	if len(csuo.hooks) == 0 {
		node, err = csuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CardStatusMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			csuo.mutation = mutation
			node, err = csuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(csuo.hooks) - 1; i >= 0; i-- {
			mut = csuo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, csuo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (csuo *CardStatusUpdateOne) SaveX(ctx context.Context) *CardStatus {
	cs, err := csuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return cs
}

// Exec executes the query on the entity.
func (csuo *CardStatusUpdateOne) Exec(ctx context.Context) error {
	_, err := csuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csuo *CardStatusUpdateOne) ExecX(ctx context.Context) {
	if err := csuo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (csuo *CardStatusUpdateOne) sqlSave(ctx context.Context) (cs *CardStatus, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cardstatus.Table,
			Columns: cardstatus.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cardstatus.FieldID,
			},
		},
	}
	id, ok := csuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "ID", err: fmt.Errorf("missing CardStatus.ID for update")}
	}
	_spec.Node.ID.Value = id
	if value, ok := csuo.mutation.DoneLast(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: cardstatus.FieldDoneLast,
		})
	}
	if csuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardstatus.UserTable,
			Columns: []string{cardstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := csuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cardstatus.UserTable,
			Columns: []string{cardstatus.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if csuo.mutation.CardCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cardstatus.CardTable,
			Columns: []string{cardstatus.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: word.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := csuo.mutation.CardIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   cardstatus.CardTable,
			Columns: []string{cardstatus.CardColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: word.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	cs = &CardStatus{config: csuo.config}
	_spec.Assign = cs.assignValues
	_spec.ScanValues = cs.scanValues()
	if err = sqlgraph.UpdateNode(ctx, csuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cardstatus.Label}
		} else if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	return cs, nil
}
