// Package ent is autogenerated by entc.
// Only files in ./schema and ./template should be edited
package ent

//go:generate go run github.com/facebookincubator/ent/cmd/entc generate --template=./template ./schema
