// Code generated by entc, DO NOT EDIT.

package ent

import (
	"flashcards-backend/ent/word"
	"fmt"
	"strings"
	"time"

	"github.com/facebookincubator/ent/dialect/sql"
)

// Word is the model entity for the Word schema.
type Word struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreateTime holds the value of the "create_time" field.
	CreateTime time.Time `json:"create_time,omitempty"`
	// UpdateTime holds the value of the "update_time" field.
	UpdateTime time.Time `json:"update_time,omitempty"`
	// Lang1 holds the value of the "lang1" field.
	Lang1 string `json:"lang1,omitempty"`
	// Lang2 holds the value of the "lang2" field.
	Lang2 string `json:"lang2,omitempty"`
	// Word1 holds the value of the "word1" field.
	Word1 string `json:"word1,omitempty"`
	// Word2 holds the value of the "word2" field.
	Word2 string `json:"word2,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the WordQuery when eager-loading is set.
	Edges WordEdges `json:"edges"`
}

// WordEdges holds the relations/edges for other nodes in the graph.
type WordEdges struct {
	// CardLogs holds the value of the cardLogs edge.
	CardLogs []*CardLog
	// CardSchedules holds the value of the cardSchedules edge.
	CardSchedules []*CardSchedule
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// CardLogsOrErr returns the CardLogs value or an error if the edge
// was not loaded in eager-loading.
func (e WordEdges) CardLogsOrErr() ([]*CardLog, error) {
	if e.loadedTypes[0] {
		return e.CardLogs, nil
	}
	return nil, &NotLoadedError{edge: "cardLogs"}
}

// CardSchedulesOrErr returns the CardSchedules value or an error if the edge
// was not loaded in eager-loading.
func (e WordEdges) CardSchedulesOrErr() ([]*CardSchedule, error) {
	if e.loadedTypes[1] {
		return e.CardSchedules, nil
	}
	return nil, &NotLoadedError{edge: "cardSchedules"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Word) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{},  // id
		&sql.NullTime{},   // create_time
		&sql.NullTime{},   // update_time
		&sql.NullString{}, // lang1
		&sql.NullString{}, // lang2
		&sql.NullString{}, // word1
		&sql.NullString{}, // word2
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Word fields.
func (w *Word) assignValues(values ...interface{}) error {
	if m, n := len(values), len(word.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	w.ID = int(value.Int64)
	values = values[1:]
	if value, ok := values[0].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field create_time", values[0])
	} else if value.Valid {
		w.CreateTime = value.Time
	}
	if value, ok := values[1].(*sql.NullTime); !ok {
		return fmt.Errorf("unexpected type %T for field update_time", values[1])
	} else if value.Valid {
		w.UpdateTime = value.Time
	}
	if value, ok := values[2].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field lang1", values[2])
	} else if value.Valid {
		w.Lang1 = value.String
	}
	if value, ok := values[3].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field lang2", values[3])
	} else if value.Valid {
		w.Lang2 = value.String
	}
	if value, ok := values[4].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field word1", values[4])
	} else if value.Valid {
		w.Word1 = value.String
	}
	if value, ok := values[5].(*sql.NullString); !ok {
		return fmt.Errorf("unexpected type %T for field word2", values[5])
	} else if value.Valid {
		w.Word2 = value.String
	}
	return nil
}

// QueryCardLogs queries the cardLogs edge of the Word.
func (w *Word) QueryCardLogs() *CardLogQuery {
	return (&WordClient{config: w.config}).QueryCardLogs(w)
}

// QueryCardSchedules queries the cardSchedules edge of the Word.
func (w *Word) QueryCardSchedules() *CardScheduleQuery {
	return (&WordClient{config: w.config}).QueryCardSchedules(w)
}

// Update returns a builder for updating this Word.
// Note that, you need to call Word.Unwrap() before calling this method, if this Word
// was returned from a transaction, and the transaction was committed or rolled back.
func (w *Word) Update() *WordUpdateOne {
	return (&WordClient{config: w.config}).UpdateOne(w)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (w *Word) Unwrap() *Word {
	tx, ok := w.config.driver.(*txDriver)
	if !ok {
		panic("ent: Word is not a transactional entity")
	}
	w.config.driver = tx.drv
	return w
}

// String implements the fmt.Stringer.
func (w *Word) String() string {
	var builder strings.Builder
	builder.WriteString("Word(")
	builder.WriteString(fmt.Sprintf("id=%v", w.ID))
	builder.WriteString(", create_time=")
	builder.WriteString(w.CreateTime.Format(time.ANSIC))
	builder.WriteString(", update_time=")
	builder.WriteString(w.UpdateTime.Format(time.ANSIC))
	builder.WriteString(", lang1=")
	builder.WriteString(w.Lang1)
	builder.WriteString(", lang2=")
	builder.WriteString(w.Lang2)
	builder.WriteString(", word1=")
	builder.WriteString(w.Word1)
	builder.WriteString(", word2=")
	builder.WriteString(w.Word2)
	builder.WriteByte(')')
	return builder.String()
}

// Words is a parsable slice of Word.
type Words []*Word

func (w Words) config(cfg config) {
	for _i := range w {
		w[_i].config = cfg
	}
}
