// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// Word is the predicate function for word builders.
type Word func(*sql.Selector)
