query FlashcardPage($newWordCount: Int!) {
  scheduledWords(newWordCount: $newWordCount) {
    cards {
      id
      lang1
      lang2
      word1
      word2
    }
  }
}

mutation SetCardStatus($cardId: ID!, $result: CardResult!) {
  cardStatus(input: { cardId: $cardId, result: $result }) {
    id
    word {
      id
    }
  }
}
