// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

// Package model is generated by gqlgen
package model

import (
	"time"
)

type NewWord struct {
	LangData string `json:"langData"`
	Word1    string `json:"word1"`
	Word2    string `json:"word2"`
}

type UpdateWord struct {
	ID    string `json:"id"`
	Word1 string `json:"word1"`
	Word2 string `json:"word2"`
}

type Word struct {
	ID        string    `json:"id"`
	LangData  string    `json:"langData"`
	Word1     string    `json:"word1"`
	Word2     string    `json:"word2"`
	CreatedAt time.Time `json:"createdAt"`
}
