// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewWord struct {
	Lang1 string `json:"lang1"`
	Lang2 string `json:"lang2"`
	Word1 string `json:"word1"`
	Word2 string `json:"word2"`
}

type UpdateWord struct {
	ID    string `json:"id"`
	Word1 string `json:"word1"`
	Word2 string `json:"word2"`
}

type Word struct {
	ID         string    `json:"id"`
	Lang1      string    `json:"lang1"`
	Lang2      string    `json:"lang2"`
	Word1      string    `json:"word1"`
	Word2      string    `json:"word2"`
	CreateTime time.Time `json:"createTime"`
	UpdateTime time.Time `json:"updateTime"`
}
