export interface Word {
  fi: string;
  en: string;
}
export const wordList: Word[] = [
  { fi: "Finnish", en: "Suomenkieli" },
  { fi: "äidinkieli", en: "mother tongue" },
  { fi: "ajaa", en: "drive" },
  { fi: "anteeksi", en: "excuse me/sorry" },
  { fi: "arkkitehti", en: "architect" },
  { fi: "astetta", en: "degrees" },
  { fi: "asua", en: "live, reside" },
  { fi: "aurinko", en: "sun" },
  { fi: "auto", en: "car" },
  { fi: "Brasilialainen", en: "Brazilian" },
  { fi: "bussikuski", en: "bus driver" },
  { fi: "bussipysäkille", en: "to the bus stop" },
  { fi: "diftongit", en: "diphthong" },
  { fi: "diskossa", en: "disco" },
  { fi: "ei se mitään", en: "no problem" },
  { fi: "eilen", en: "yesterday" },
  { fi: "elokuussa", en: "August" },
  { fi: "Entä sinulle?", en: "How about you?" },
  { fi: "etelä", en: "south" },
  { fi: "etsiä", en: "search" },
  { fi: "että", en: "that" },
  { fi: "etunimi", en: "surname" },
  { fi: "haluaisin", en: "would want" },
  { fi: "hänellä (on)", en: "he/she (has something)" },
  { fi: "hassu", en: "funny" },
  { fi: "hauska tutustua", en: "nice to meet you" },
  { fi: "hauskaa viikonloppua!", en: "have a good weekend" },
  { fi: "heippa", en: "bye bye, see you later" },
  { fi: "huomenna", en: "tomorrow" },
  { fi: "huomenta", en: "morning" },
  { fi: "hyvää huomenta!", en: "good morning" },
  { fi: "hyvää iltaa", en: "good evening" },
  { fi: "hyvää päivää", en: "good day" },
  { fi: "hyvää yötä", en: "good night" },
  { fi: "Ihan hyvää", en: "very well" },
  { fi: "illalla", en: "in the evening" },
  { fi: "ilma", en: "climate / weather" },
  { fi: "internetistä", en: "on the internet" },
  { fi: "intonaatio", en: "intonation" },
  { fi: "istua", en: "sit" },
  { fi: "itä", en: "east" },
  { fi: "jäätelöä", en: "ice cream" },
  { fi: "jäätelökioskilla", en: "ice-cream shop" },
  { fi: "Joo", en: "yes" },
  { fi: "joskus", en: "sometimes" },
  { fi: "kanssa", en: "with" },
  { fi: "kappale ", en: "chapter/lesson" },
  { fi: "kaunis", en: "beautiful" },
  { fi: "kauppa", en: "shop" },
  { fi: "kello", en: "clock / o'clock" },
  { fi: "kesä", en: "summer" },
  { fi: "keskiviikko", en: "Wednesday" },
  { fi: "kiina", en: "china" },
  { fi: "kiitos", en: "thank you" },
  { fi: "kiitos, samoin", en: "thank you, same to you" },
  { fi: "-kin", en: " also + V" },
  { fi: "kirjoittaa", en: "write" },
  { fi: "kitara", en: "guitar" },
  { fi: "kiva", en: "nice" },
  { fi: "konsonantit", en: "consonant" },
  { fi: "koska", en: "because" },
  { fi: "koskille", en: "to the kiosk" },
  { fi: "koti", en: "house" },
  { fi: "kotiin", en: "to home" },
  { fi: "kotoisin", en: "from" },
  { fi: "kotona", en: "at home" },
  { fi: "koulussa", en: "at the school" },
  { fi: "kuinka vanha sinä olet?", en: "how old are you?" },
  { fi: "kuka sinä olet?", en: "who are you?" },
  { fi: "kursilla", en: "at course" },
  { fi: "kurssi", en: "course" },
  { fi: "kymmenen", en: "number 10" },
  { fi: "lähettäjä", en: "sender" },
  { fi: "lämmin", en: "warm" },
  { fi: "länsi", en: "west" },
  { fi: "lapsi", en: "kid/child" },
  { fi: "lauantai", en: "Saturday" },
  { fi: "loppua", en: "end / finish" },
  { fi: "luen", en: "I read" },
  { fi: "maanantai", en: "Monday" },
  { fi: "maksaa", en: "cost/pay" },
  { fi: "mansikka", en: "strawberry" },
  { fi: "meidän", en: "our" },
  { fi: "menevää", en: "go" },
  { fi: "mies", en: "man" },
  { fi: "mihin tämä bussi menee?", en: "where does this bus go?" },
  { fi: "mikä päivä tänään on?", en: "what day is it today?" },
  { fi: "mikä sinun nimi on?", en: "what is your name?" },
  { fi: "miksi et osta jäätelöä?", en: "why dont you buy ice-cream?" },
  { fi: "miljoona", en: "number 1,000,000" },
  { fi: "millainen sää on?", en: "how is the weather like?" },
  { fi: "millainen sanakirja on?", en: "how is the dictionary?" },
  { fi: "milloin kurssi on?", en: "when is the course?" },
  { fi: "minkämaalainen sinä olet?", en: "what nationality are you?" },
  { fi: "missä sinä asut?", en: "where do you live?" },
  { fi: "mistä sinä olet kotoisin?", en: "where are you from?" },
  { fi: "mitä", en: "what" },
  { fi: "mitä kieltä sinä puhut?", en: "what language do you speak?" },
  { fi: "mitä sinulle kuuluu?", en: "how have you been doing?" },
  { fi: "mitä xxx maksaa?", en: "how much does xxx cost?" },
  { fi: "miten sinun nimi kirjoitetaan?", en: "how do you spell your name" },
  { fi: "moi", en: "hi" },
  { fi: "moi moi", en: "bye bye" },
  { fi: "moikka", en: "bye" },
  { fi: "mutta", en: "but" },
  { fi: "muut", en: "other" },
  { fi: "muuttaa", en: "move" },
  { fi: "myös", en: "also" },
  { fi: "naapuri", en: "neighbor" },
  { fi: "nähdään", en: "see  you" },
  { fi: "nähdään huomenna", en: "see you  tomorrow" },
  { fi: "naimisiin", en: "get married" },
  { fi: "naimisissa", en: "married to" },
  { fi: "napa", en: "belly button" },
  { fi: "nauraa", en: "laugh" },
  { fi: "nimi", en: "name" },
  { fi: "nukkua", en: "sleep" },
  { fi: "nuku hyvin", en: "sleep well" },
  { fi: "numerot", en: "numbers" },
  { fi: "nyt", en: "now" },
  { fi: "ole hyvä", en: "you are welcome" },
  { fi: "opettaja", en: "teacher" },
  { fi: "opiskelija", en: "student (singular)" },
  { fi: "opiskella", en: "study" },
  { fi: "opiskelija-asunnossa", en: "at the student apartment" },
  { fi: "opiskelijat", en: "students (plural)" },
  { fi: "ostaa", en: "buy" },
  { fi: "otsikko", en: "subject (email)" },
  { fi: "paistaa", en: "shine" },
  { fi: "päiväkodissa", en: "at the day care center" },
  { fi: "päiväkoti", en: "day care center" },
  { fi: "päivällä", en: "during the day" },
  { fi: "paljon", en: "very much" },
  { fi: "pallo", en: "ball" },
  { fi: "pankissa", en: "at the bank" },
  { fi: "perhe", en: "family" },
  { fi: "perjantai", en: "Friday" },
  { fi: "phjoisnapa", en: "north pole" },
  { fi: "pieni", en: "small" },
  { fi: "puhelinta", en: "(use) phone" },
  { fi: "puhua", en: "speak / chat" },
  { fi: "puistossa", en: "at the park" },
  { fi: "sää", en: "weather" },
  { fi: "sähköposti", en: "email" },
  { fi: "samalla", en: "at same time" },
  { fi: "samoin", en: "the same" },
  { fi: "sanapaino", en: "stress" },
  { fi: "sanasto", en: "vocabulary" },
  { fi: "sata", en: "number 100" },
  { fi: "selvä", en: "alright" },
  { fi: "siksi", en: "therefore" },
  { fi: "sitten", en: "then" },
  { fi: "soittaa", en: "play" },
  { fi: "suklaajäätelöä", en: "chocolate ice-cream" },
  { fi: "sukunimi", en: "last name" },
  { fi: "sunnuntai", en: "Sunday" },
  { fi: "Suomalainen (adj)", en: "Finnish" },
  { fi: "Suomi", en: "Finland-finnish language" },
  { fi: "täällä", en: "here" },
  { fi: "tänään", en: "today" },
  { fi: "tanssia", en: "dance" },
  { fi: "tässä", en: "here" },
  { fi: "tavallinen", en: "typical" },
  { fi: "terve", en: "hello" },
  { fi: "terveisin", en: "with regards" },
  { fi: "tervetuloa", en: "welcome" },
  { fi: "tietysti", en: "of course" },
  { fi: "tiistai", en: "Tuesday" },
  { fi: "töissä", en: "work" },
  { fi: "toissapäivänä", en: "the day before yesterday" },
  { fi: "töitä", en: "jobs" },
  { fi: "toivottavasti", en: "hope" },
  { fi: "torstai", en: "Thursday" },
  { fi: "tuhat", en: "number 1,000" },
  { fi: "tulla", en: "come" },
  { fi: "tuleeko muuta?", en: "Anything else?" },
  { fi: "tutustuminen", en: "introduction" },
  { fi: "tyttöystävä", en: "girlfriend" },
  { fi: "uusi", en: "new" },
  { fi: "uutiset", en: "news" },
  { fi: "vaan", en: "something but something" },
  { fi: "vaikea", en: "difficult" },
  { fi: "valoisaa", en: "bright" },
  { fi: "liian valoisaa", en: "too bright" },
  { fi: "vanilja", en: "vanilla" },
  { fi: "vastaanottaja", en: "recipient" },
  { fi: "venäläinen", en: "Russian (nationality)" },
  { fi: "viikonloppu", en: "weekend" },
  { fi: "vokaalit", en: "vowel" },
  { fi: "vuotias", en: "year-old" },
  { fi: "vuotta", en: "years old" },
  { fi: "yleensä", en: "usually" },
  { fi: "ylihuomenna", en: "the day after tomorrow" },
  { fi: "yliopisto", en: "university" },
  { fi: "ymmärtää", en: "understand" },
  { fi: "yöllä", en: "at night" },
  { fi: "yrityksessä", en: "company" },
  { fi: "ystävä", en: "friend" },
  { fi: "hyvä", en: "good" },
  { fi: "huono", en: "bad" },
  { fi: "kuuma", en: "hot" },
  { fi: "kylmä", en: "cold / iced" },
  { fi: "vaikea", en: "difficult" },
  { fi: "helppo", en: "easy" },
  { fi: "uusi", en: "new" },
  { fi: "vanha", en: "old" },
  { fi: "pieni", en: "small" },
  { fi: "iso", en: "big" },
  { fi: "suuri", en: "big" },
  { fi: "kaunis", en: "beautiful" },
  { fi: "ruma", en: "ugly" },
  { fi: "lämmin", en: "warm" },
  { fi: "viileä", en: "cold" },
  { fi: "valoisa", en: "bright" },
  { fi: "pimeä", en: "dark" },
  { fi: "vähän", en: "little" },
  {
    fi: "kuinka monta astetta ulkona on?",
    en: "how many degree is it outside?",
  },
  { fi: "ulkona", en: "outside" },
  { fi: "helle", en: "very hot" },
  { fi: "pakkasta", en: "freezing cold" },
  { fi: "aurinkoista", en: "sunny" },
  { fi: "pilvistä", en: "cloudy" },
  { fi: "puolipilvistä", en: "half cloudy" },
  { fi: "selkeää", en: "no cloud" },
  { fi: "sumuista", en: "foggy" },
  { fi: "sataa", en: "rain" },
  { fi: "sateista", en: "rainy" },
  { fi: "sataa räntää", en: "wet snow" },
  { fi: "sataa lunta", en: "snow" },
  { fi: "tuulee", en: "wind" },
  { fi: "tuulista", en: "windy" },
  { fi: "myrsky", en: "storm" },
  { fi: "ukkonen", en: "lighting and thunderstorm" },
  { fi: "aamulla", en: "during the morning" },
  { fi: "aamupäivällä", en: "during the time before midday" },
  { fi: "päivällä", en: "during the day" },
  { fi: "iltapäivällä", en: "during the afternoon" },
  { fi: "illalla", en: "during the evening" },
  { fi: "yöllä", en: "during the night" },
  { fi: "aamuyöllä", en: "during the time before morning" },
  { fi: "talvi", en: "(season) winter" },
  { fi: "kevät", en: "(season) spring" },
  { fi: "kesä", en: "(season) summer" },
  { fi: "syksy", en: "(season) autumn" },
  { fi: "värit", en: "color" },
  { fi: "valkoinen", en: "white" },
  { fi: "musta", en: "black" },
  { fi: "punainen", en: "red" },
  { fi: "ruskea", en: "brown" },
  { fi: "sininen", en: "blue" },
  { fi: "harmaa", en: "grey" },
  { fi: "keltäinen", en: "yellow" },
  { fi: "oranssi", en: "orange" },
  { fi: "vihreä", en: "green" },
  { fi: "liila", en: "violet / purple" },
  { fi: "meri", en: "sea" },
  { fi: "banaani", en: "banana" },
  { fi: "pilvi", en: "cloud" },
  { fi: "tomaatti", en: "tomato" },
  { fi: "appelsiini", en: "orange" },
  { fi: "salaatti", en: "salad" },
  { fi: "voitko auttaa minua?", en: "can you help me?" },
  { fi: "suomeksi", en: "in finnish language" },
  { fi: "tiedää", en: "know" },
  { fi: "en tiedä", en: "I dont know" },
  { fi: "sanotaa", en: "say" },
  { fi: "terveisiä", en: "greetings from" },
  { fi: "sanoa", en: "say" },
  { fi: "uudelleen", en: "again" },
  { fi: "kiitos avusta", en: "thanks for your help" },
  { fi: "voitko puhua hitaasti?", en: "can you speak it slowly?" },
  { fi: "hitaasti", en: "slowly" },
  { fi: "voitko sanoa uudellen?", en: "can you say it again?" },
  { fi: "miten sanotaan ... Suomeksi?", en: "how do I say ... in Finnish?" },
  { fi: "Mitä ... on suomeksi?", en: "what is .... in Finnish?" },
  { fi: "En ymmärrä", en: "I dont understand" },
  { fi: "avusta", en: "help" },
  { fi: "minkävärinen", en: "what color" },
  { fi: "minkävärinen ... on?", en: "what color is ...?" },
  { fi: "kesällä", en: "in summer" },
  { fi: "harjoitus", en: "practice" },
  { fi: "kaupunki", en: "town/city" },
  { fi: "sataa", en: "rain" },
  { fi: "sataa lunta", en: "raining snow" },
  { fi: "kirkko", en: "church" },
  { fi: "meri", en: "sea" },
  { fi: "kysy", en: "ask" },
  { fi: "lue", en: "read" },
  { fi: "vuodenaika", en: "season" },
  { fi: "normaalisti", en: "normally" },
  { fi: "maassa", en: "on the ground" },
  { fi: "maa", en: "land/country" },
  { fi: "aina", en: "always" },
  { fi: "usein", en: "often" },
  { fi: "loskasää", en: "wet snow weather" },
  { fi: "suomalaiset", en: "Finnish people" },
  { fi: "hiihtää", en: "skii" },
  { fi: "luistella", en: "ice-skating" },
  { fi: "lyhyt", en: "short" },
  { fi: "pikä", en: "long" },
  { fi: "vain", en: "only" },
  { fi: "pari", en: "pair" },
  { fi: "tunti", en: "hour" },
  { fi: "koko päivän", en: "the whole day" },
  { fi: "huhtikuussa", en: "in April" },
  { fi: "huhtikuu", en: "April" },
  { fi: "räntää", en: "wet snow / rain and snow mixed" },
  { fi: "toukokuu", en: "May" },
  { fi: "toukokuussa", en: "in May" },
  { fi: "aika", en: "time" },
  { fi: "on jo", en: "already" },
  { fi: "puut", en: "trees" },
  { fi: "vihreät", en: "green (plural subject)" },
  { fi: "kukkia", en: "blooming" },
  { fi: "tulppaanit", en: "tulips" },
  { fi: "tulppaani", en: "a tulip" },
  { fi: "narsissit", en: "daffodils" },
  { fi: "narsissi", en: "daffodil" },
  { fi: "lapset", en: "children" },
  { fi: "kesäloma", en: "summer vacation" },
  { fi: "ihmiset", en: "people" },
  { fi: "kesämökillä", en: "in the summer house / cottage" },
  { fi: "kesämökki", en: "summer house" },
  { fi: "uida", en: "swim" },
  { fi: "värit", en: "colors" },
  { fi: "syyskuussa", en: "in September" },
  { fi: "syyskuu", en: "September" },
  { fi: "metsään", en: "forests" },
  { fi: "marjat", en: "berries" },
  { fi: "sienet", en: "mushrooms" },
  { fi: "odottaa", en: "wait" },
  { fi: "lokakuussa", en: "in October" },
  { fi: "lokakuu", en: "October" },
  { fi: "marraskuussa", en: "in November" },
  { fi: "marraskuu", en: "November" },
  { fi: "vettä", en: "water" },
  { fi: "syntymäpäivä", en: "birthday" },
  { fi: "poliisi", en: "police" },
  { fi: "poikaystävä", en: "boyfriend" },
  { fi: "tyttöystävä", en: "girlfriend" },
  { fi: "talo", en: "house" },
  { fi: "kotimaa", en: "home country" },
  { fi: "isoäiti", en: "grandmother" },
  { fi: "pääkaupunki", en: "capital city" },
  { fi: "presidentti", en: "president" },
  { fi: "katu", en: "street" },
  { fi: "tauko", en: "break" },
  { fi: "teksti", en: "text" },
  { fi: "allka", en: "start" },
  { fi: "ehkä", en: "perhaps" },
  { fi: "kirja", en: "a book" },
  { fi: "kenen", en: "whose" },
  { fi: "maa", en: "country" },
  { fi: "lahteä", en: "go" },
  { fi: "nuku", en: "sleep" },
  { fi: "pitkään", en: "at length" },
  { fi: "saapua", en: "arrive" },
  { fi: "lentokoneella", en: "by plane" },
  { fi: "lukea", en: "read" },
  { fi: "lentää", en: "fly" },
  { fi: "sanoa", en: "say" },
  { fi: "keskustaan", en: "downtown" },
  { fi: "katsoa", en: "look" },
  { fi: "ottaa", en: "take" },
  { fi: "monta", en: "many" },
  { fi: "kartan", en: "a map" },
  { fi: "kertoa", en: "tell" },
  { fi: "löytää", en: "find" },
  { fi: "heti", en: "immediately" },
  { fi: "soittaa", en: "call" },
  { fi: "yöpyä", en: "stay / sleep" },
  { fi: "olla naimisissa", en: "get married" },
  { fi: "AAA kanssa", en: "with AAA" },
  { fi: "meillä", en: "we have" },
  { fi: "lapsi", en: "a child" },
  { fi: "söpö", en: "cute" },
  { fi: "vuotias", en: "year-old" },
  { fi: "tyttö", en: "girl" },
  { fi: "minulla ei ole töitä", en: "I dont have a job" },
  { fi: "vielä", en: "yet" },
  { fi: "työpaikkaa", en: "jobs" },
  { fi: "kanssa", en: "with" },
  { fi: "pitkä", en: "tall" },
  { fi: "hoikka", en: "slim" },
  { fi: "ujo", en: "shy" },
  { fi: "vaalea", en: "blond" },
  { fi: "tukka", en: "hair" },
  { fi: "siniset", en: "blue (for plural nouns)" },
  { fi: "silmät", en: "eyes" },
  { fi: "minulla ei ole perhettä", en: "I dont have family" },
  { fi: "äiti", en: "mom" },
  { fi: "isä", en: "dad" },
  { fi: "isoveli", en: "big brother" },
  { fi: "pikkusisko", en: "little sister" },
  { fi: "helsinkiläinen", en: "Helsinki citizen" },
  { fi: "talossa", en: "apartment building" },
  { fi: "kerrosta", en: "floors" },
  { fi: "kerros", en: "a floor" },
  { fi: "huonetta", en: "rooms" },
  { fi: "huone", en: "a room" },
  { fi: "keittiö", en: "kitchen" },
  { fi: "puhelias", en: "chatty" },
  { fi: "iloinen", en: "happy/cheerful" },
  { fi: "kihara", en: "curly" },
  { fi: "tummat", en: "dark" },
  { fi: "pyörä", en: "bicycle" },
  { fi: "surullinen", en: "sad" },
  { fi: "hiljainen", en: "quiet / not talkative" },
  { fi: "vihainen", en: "angry" },
  { fi: "ystävällinen", en: "friendly" },
  { fi: "kohtelias", en: "friendly" },
  { fi: "epäystävällinen", en: "unfriendly" },
  { fi: "epäkohtelias", en: "unfriendly" },
  { fi: "nuori", en: "young" },
  { fi: "vanha", en: "old" },
  { fi: "ujo", en: "shy" },
  { fi: "minkänäköinen hän on?", en: "how does (s)he look like?" },
  { fi: "hänellä on", en: "(s)he has" },
  { fi: "suora", en: "straight" },
  { fi: "silmälasit", en: "eyeglasses" },
  { fi: "nätti", en: "pretty" },
  { fi: "hyvännäköinen", en: "good looking" },
  { fi: "kalju", en: "bald" },
  { fi: "parta", en: "beard" },
  { fi: "viikset", en: "mustache" },
  { fi: "komea", en: "handsome" },
  { fi: "tukeva", en: "chubby" },
  { fi: "suloinen", en: "sweet" },
  { fi: "isovanhemmat", en: "grandparents" },
  { fi: "isoisä", en: "grandad" },
  { fi: "isoäiti", en: "grandmom" },
  { fi: "mies", en: "husband" },
  { fi: "vaimo", en: "wife" },
  { fi: "isä", en: "dad" },
  { fi: "äiti", en: "mom" },
  { fi: "vanhemmat", en: "parents" },
  { fi: "veli", en: "brother" },
  { fi: "sisko", en: "sister" },
  { fi: "poika", en: "son" },
  { fi: "tytär", en: "daughter" },
  { fi: "vauva", en: "baby" },
  { fi: "naimaton", en: "single" },
  { fi: "sinkku", en: "single" },
  { fi: "kihloissa", en: "engaged" },
  { fi: "eronnut", en: "divorced" },
  { fi: "työtön", en: "unemployed" },
  { fi: "eläkkeellä", en: "retired" },
];
