export interface Word {
  fi: string;
  en: string;
}
export const words: Word[] = [
  { fi: "Finnish", en: "English" },
  { fi: "äidinkieli", en: "mother tounge" },
  { fi: "ajaa", en: "drive" },
  { fi: "anteeksi", en: "excuse me/sorry" },
  { fi: "arkkitehti", en: "architect" },
  { fi: "astetta", en: "degrees" },
  { fi: "asua", en: "live, reside" },
  { fi: "aurinko", en: "sun" },
  { fi: "auto", en: "car" },
  { fi: "Brasilialainen", en: "Brazilian" },
  { fi: "bussikuski", en: "bus driver" },
  { fi: "bussipysäkille", en: "to the bus stop" },
  { fi: "diftongit", en: "diphthong" },
  { fi: "diskossa", en: "disco" },
  { fi: "ei se mitään", en: "no problem" },
  { fi: "eilen", en: "yesterday" },
  { fi: "elokuussa", en: "August" },
  { fi: "Entä sinulle?", en: "How about you?" },
  { fi: "etelä", en: "south" },
  { fi: "etsiä", en: "search" },
  { fi: "että", en: "that" },
  { fi: "etunimi", en: "surname" },
  { fi: "haluaisin", en: "would want" },
  { fi: "hänellä (on)", en: "he/she (has something)" },
  { fi: "hassu", en: "funny" },
  { fi: "hauska tutustua", en: "nice to meet you" },
  { fi: "hauskaa viikonloppua!", en: "have a good weekend" },
  { fi: "heippa", en: "bye bye, see you later" },
  { fi: "huomenna", en: "tomorrow" },
  { fi: "huomenta", en: "morning" },
  { fi: "hyvää huomenta!", en: "good morning" },
  { fi: "hyvää iltaa", en: "good evening" },
  { fi: "hyvää päivää", en: "good day" },
  { fi: "hyvää yötä", en: "good night" },
  { fi: "Ihan hyvää", en: "very well" },
  { fi: "illalla", en: "in the evening" },
  { fi: "ilma", en: "climate / weather" },
  { fi: "internetistä", en: "on the internet" },
  { fi: "intonaatio", en: "intonation" },
  { fi: "istua", en: "sit" },
  { fi: "itä", en: "east" },
  { fi: "jäätelöä", en: "ice cream" },
  { fi: "jäätelökioskilla", en: "ice-cream shop" },
  { fi: "Joo", en: "yes" },
  { fi: "joskus", en: "sometimes" },
  { fi: "kanssa", en: "with" },
  { fi: "kappale ", en: "chapter/lesson" },
  { fi: "kaunis", en: "beautiful" },
  { fi: "kauppa", en: "shop" },
  { fi: "kello", en: "clock / o'clock" },
  { fi: "kesä", en: "summer" },
  { fi: "keskiviikko", en: "Wednesday" },
  { fi: "kiina", en: "china" },
  { fi: "kiitos", en: "thank you" },
  { fi: "kiitos, samoin", en: "thank you, same to you" },
  { fi: "-kin", en: " also + V" },
  { fi: "kirjoittaa", en: "write" },
  { fi: "kitara", en: "guitar" },
  { fi: "kiva", en: "nice" },
  { fi: "konsonantit", en: "consonant" },
  { fi: "koska", en: "because" },
  { fi: "koskille", en: "to the kiosk" },
  { fi: "koti", en: "house" },
  { fi: "kotiin", en: "to home" },
  { fi: "kotoisin", en: "from" },
  { fi: "kotona", en: "at home" },
  { fi: "koulussa", en: "at the school" },
  { fi: "kuinka vanha sinä olet?", en: "how old are you?" },
  { fi: "kuka sinä olet?", en: "who are you?" },
  { fi: "kursilla", en: "at course" },
  { fi: "kurssi", en: "course" },
  { fi: "kymmenen", en: "number 10" },
  { fi: "lähettäjä", en: "sender" },
  { fi: "lämmin", en: "warm" },
  { fi: "länsi", en: "west" },
  { fi: "lapsi", en: "kid/child" },
  { fi: "lauantai", en: "Saturday" },
  { fi: "loppua", en: "end / finish" },
  { fi: "luen", en: "I read" },
  { fi: "maanantai", en: "Monday" },
  { fi: "maksaa", en: "cost/pay" },
  { fi: "mansikka", en: "strawberry" },
  { fi: "meidän", en: "our" },
  { fi: "menevää", en: "go" },
  { fi: "mies", en: "man" },
  { fi: "mihin tämä bussi menee?", en: "where does this bus go?" },
  { fi: "mikä päivä tänään on?", en: "what day is it today?" },
  { fi: "mikä sinun nimi on?", en: "what is your name?" },
  { fi: "miksi et osta jäätelöä?", en: "why dont you buy ice-cream?" },
  { fi: "miljoona", en: "number 1,000,000" },
  { fi: "millainen sää on?", en: "how is the weather like?" },
  { fi: "millainen sanakirja on?", en: "how is the dictionary?" },
  { fi: "milloin kurssi on?", en: "when is the course?" },
  { fi: "minkämaalainen sinä olet?", en: "what nationality are you?" },
  { fi: "missä sinä asut?", en: "where do you live?" },
  { fi: "mistä sinä olet kotoisin?", en: "where are you from?" },
  { fi: "mitä", en: "what" },
  { fi: "mitä kieltä sinä puhut?", en: "what language do you speak?" },
  { fi: "mitä sinulle kuuluu?", en: "how have you been doing?" },
  { fi: "mitä xxx maksaa?", en: "how much does xxx cost?" },
  { fi: "miten sinun nimi kirjoitetaan?", en: "how do you spell your name" },
  { fi: "moi", en: "hi" },
  { fi: "moi moi", en: "bye bye" },
  { fi: "moikka", en: "bye" },
  { fi: "mutta", en: "but" },
  { fi: "muut", en: "other" },
  { fi: "muuttaa", en: "move" },
  { fi: "myös", en: "also" },
  { fi: "naapuri", en: "neighbor" },
  { fi: "nähdään", en: "see  you" },
  { fi: "nähdään huomenna", en: "see you  tomorrow" },
  { fi: "naimisiin", en: "get married" },
  { fi: "naimisissa", en: "married to" },
  { fi: "napa", en: "belly button" },
  { fi: "nauraa", en: "laugh" },
  { fi: "nimi", en: "name" },
  { fi: "nukkua", en: "sleep" },
  { fi: "nuku hyvin", en: "sleep well" },
  { fi: "numerot", en: "numbers" },
  { fi: "nyt", en: "now" },
  { fi: "ole hyvä", en: "you are welcome" },
  { fi: "opettaja", en: "teacher" },
  { fi: "opiskelija", en: "student (singular)" },
  { fi: "opiskella", en: "study" },
  { fi: "opiskelija-asunnossa", en: "at the student apartment" },
  { fi: "opiskelijat", en: "students (plural)" },
  { fi: "ostaa", en: "buy" },
  { fi: "otsikko", en: "subject (email)" },
  { fi: "paistaa", en: "shine" },
  { fi: "päiväkodissa", en: "at the day care center" },
  { fi: "päiväkoti", en: "day care center" },
  { fi: "päivällä", en: "during the day" },
  { fi: "paljon", en: "very much" },
  { fi: "pallo", en: "ball" },
  { fi: "pankissa", en: "at the bank" },
  { fi: "perhe", en: "family" },
  { fi: "perjantai", en: "Friday" },
  { fi: "phjoisnapa", en: "north pole" },
  { fi: "pieni", en: "small" },
  { fi: "puhelinta", en: "(use) phone" },
  { fi: "puhua", en: "speak / chat" },
  { fi: "puistossa", en: "at the park" },
  { fi: "sää", en: "weather" },
  { fi: "sähköposti", en: "email" },
  { fi: "samalla", en: "at same time" },
  { fi: "samoin", en: "the same" },
  { fi: "sanapaino", en: "stress" },
  { fi: "sanasto", en: "vocabulary" },
  { fi: "sata", en: "number 100" },
  { fi: "selvä", en: "alright" },
  { fi: "siksi", en: "therefore" },
  { fi: "sitten", en: "then" },
  { fi: "soittaa", en: "play" },
  { fi: "suklaajäätelöä", en: "chocolate ice-cream" },
  { fi: "sukunimi", en: "last name" },
  { fi: "sunnuntai", en: "Sunday" },
  { fi: "Suomalainen (adj)", en: "Finnish" },
  { fi: "Suomi", en: "Finland-finnish language" },
  { fi: "täällä", en: "here" },
  { fi: "tänään", en: "today" },
  { fi: "tanssia", en: "dance" },
  { fi: "tässä", en: "here" },
  { fi: "tavallinen", en: "typical" },
  { fi: "terve", en: "hello" },
  { fi: "terveisin", en: "with regards" },
  { fi: "tervetuloa", en: "welcome" },
  { fi: "tietysti", en: "of course" },
  { fi: "tiistai", en: "Tuesday" },
  { fi: "töissä", en: "work" },
  { fi: "toissapäivänä", en: "the day before yesterday" },
  { fi: "töitä", en: "jobs" },
  { fi: "toivottavasti", en: "hope" },
  { fi: "torstai", en: "Thursday" },
  { fi: "tuhat", en: "number 1,000" },
  { fi: "tulla", en: "come" },
  { fi: "tuleeko muuta?", en: "Anything else?" },
  { fi: "tutustuminen", en: "introduction" },
  { fi: "tyttöystävä", en: "girlfriend" },
  { fi: "uusi", en: "new" },
  { fi: "uutiset", en: "news" },
  { fi: "vaan", en: "something but something" },
  { fi: "vaikea", en: "difficult" },
  { fi: "valoisaa", en: "bright" },
  { fi: "liian valoisaa", en: "too bright" },
  { fi: "vanilja", en: "vanilla" },
  { fi: "vastaanottaja", en: "recipient" },
  { fi: "venäläinen", en: "Russian (nationality)" },
  { fi: "viikonloppu", en: "weekend" },
  { fi: "vokaalit", en: "vowel" },
  { fi: "vuotias", en: "year-old" },
  { fi: "vuotta", en: "years old" },
  { fi: "yleensä", en: "usually" },
  { fi: "ylihuomenna", en: "the day after tomorrow" },
  { fi: "yliopisto", en: "university" },
  { fi: "ymmärtää", en: "understand" },
  { fi: "yöllä", en: "at night" },
  { fi: "yrityksessä", en: "company" },
  { fi: "ystävä", en: "friend" },
];
