// Code generated by entc, DO NOT EDIT.

package word

import (
	"time"
)

const (
	// Label holds the string label denoting the word type in the database.
	Label = "word"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldLangData holds the string denoting the langdata field in the database.
	FieldLangData = "lang_data"
	// FieldWord1 holds the string denoting the word1 field in the database.
	FieldWord1 = "word1"
	// FieldWord2 holds the string denoting the word2 field in the database.
	FieldWord2 = "word2"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"

	// Table holds the table name of the word in the database.
	Table = "words"
)

// Columns holds all SQL columns for word fields.
var Columns = []string{
	FieldID,
	FieldLangData,
	FieldWord1,
	FieldWord2,
	FieldCreatedAt,
}

var (
	// LangDataValidator is a validator for the "langData" field. It is called by the builders before save.
	LangDataValidator func(string) error
	// Word1Validator is a validator for the "word1" field. It is called by the builders before save.
	Word1Validator func(string) error
	// Word2Validator is a validator for the "word2" field. It is called by the builders before save.
	Word2Validator func(string) error
	// DefaultCreatedAt holds the default value on creation for the created_at field.
	DefaultCreatedAt func() time.Time
)
