mutation AddWord($word1: String!, $word2: String!) {
  createWord(
    input: { lang1: "fi", lang2: "en", word1: $word1, word2: $word2 }
  ) {
    id
    word1
    word2
  }
}

mutation DeleteWord($id: ID!) {
  deleteWord(id: $id)
}

mutation EditWord($id: ID!, $word1: String!, $word2: String!) {
  updateWord(
    input: { id: $id, word1: $word1, word2: $word2, lang1: "fi", lang2: "en" }
  ) {
    id
  }
}
