// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"github.com/facebookincubator/ent/dialect/sql"
)

// CardStatus is the predicate function for cardstatus builders.
type CardStatus func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Word is the predicate function for word builders.
type Word func(*sql.Selector)
