// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"github.com/facebookincubator/ent/dialect/sql/schema"
	"github.com/facebookincubator/ent/schema/field"
)

var (
	// WordsColumns holds the columns for the "words" table.
	WordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "lang_data", Type: field.TypeString, Size: 15},
		{Name: "word1", Type: field.TypeString, Size: 255},
		{Name: "word2", Type: field.TypeString, Size: 255},
		{Name: "created_at", Type: field.TypeTime},
	}
	// WordsTable holds the schema information for the "words" table.
	WordsTable = &schema.Table{
		Name:        "words",
		Columns:     WordsColumns,
		PrimaryKey:  []*schema.Column{WordsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WordsTable,
	}
)

func init() {
}
