name: Backend CI
on:
  push:
    paths:
    - 'flashcards-backend/**.go'
    branches:
    - 'master'
  pull_request:
    paths:
    - 'flashcards-backend/**.go'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: "1"
    defaults:
      run:
        working-directory: flashcards-backend
    steps:
     - uses: actions/checkout@v2
     - name: Run unit tests
       run: make test
     - name: Build Linux binary
       run: make 
  lint:
    name: Lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: flashcards-backend
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v1.2.1
        with:
          version: latest
