name: Backend CI
on:
  push:
    paths:
    - 'flashcards-backend/**.go'
    branches:
    - 'master'
  pull_request:
    paths:
    - 'flashcards-backend/**.go'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: "1"
    defaults:
      run:
        working-directory: flashcards-backend
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Run linter
       run: make lint
     - name: Run unit tests
       run: make test
     - name: Build Linux binary
       run: make 